name: Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test Python
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    env:
      wd: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        env:
          pyversion: ${{ matrix.python-version }}
        run: uv python install "$pyversion"

      - name: Get requirements
        working-directory: ${{env.wd}}
        run: uv sync --group dev --frozen

      - name: Linting, formatting, and type checking
        working-directory: ${{env.wd}}
        run: uv run pre-commit run --show-diff-on-failure --all-files

      - name: Test
        working-directory: ${{env.wd}}
        run: uv run pytest -v
